### ISSUE TITLE
Relay and mean well driver

### ISSUE THREAD

**Issue by bobo-le** [growboxguy/Gbox420#1]
Hey, are you using the "HLG-185H-C700B" driver with 273V on your relay to turn on and off the lights?
Because the datasheet of the relay tells a max allowable voltage from 250V.
Or ist this acceptable?

Thank you

**Comment by moonberry-pl** [comment]
Yes it's OK. Relays switch AC mains (110V - 220 V) and not DC output delivered to COB

**Comment by bobo-le** [comment]
Ahh yes for sure.. thank you
